### PR TITLE
use .. from EllipsisNotation.jl

### LINKED ISSUE #18: Compatibility with EllipsisNotation
I was wondering if .. can be shared between  EllipsisNotation and Intervalsets via call overload:
```
type DotDot
end

const .. = DotDot
..(x,y) = dotdot(x,y)
```

### PR DESCRIPTION
**Pull request by mcabbott**
Closes #18

### CODE REVIEW

**Comment by mcabbott** [comment]
Test failure on 1.0 appears to be caused by this list not being empty:
```
julia> using Test, EllipsisNotation; detect_ambiguities(EllipsisNotation, Base, Core)
2-element Array{Tuple{Method,Method},1}:
 (getindex(A::AbstractArray, ::EllipsisNotation.Ellipsis) in EllipsisNotation at /Users/me/.julia/dev/EllipsisNotation/src/EllipsisNotation.jl:25, getindex(v::JSON.Parser.PushVector, i) in JSON.Parser at /Users/me/.julia/packages/JSON/d89fA/src/pushvector.jl:15)                        
 (getindex(A::AbstractArray, ::EllipsisNotation.Ellipsis) in EllipsisNotation at /Users/me/.julia/dev/EllipsisNotation/src/EllipsisNotation.jl:25, getindex(a::GenericArray, i...) in Test at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1553)
```
I think the offending line is [this](https://github.com/ChrisRackauckas/EllipsisNotation.jl/blob/master/src/EllipsisNotation.jl#L25
):
```
Base.getindex(A::AbstractArray, ::Ellipsis) = A
```
This list is not empty on 1.3 either, but that didn’t cause an error. I’m not entirely sure why this sees the package JSON at all.

**Comment by mcabbott** [comment]
`JSON` was being loaded by `BenchmarkTools` in my statup. On 1.0 the remaining ambiguity warning is from `getindex(a::GenericArray, i...)` defined by `Test`, which was must have been removed from later versions. I’ve simply disabled that test on 1.0 now.

**Comment by dlfivefifty** [comment]
This looks fine for me, just bump the version number.

**Comment by mcabbott** [comment]
Great! Is a minor increment enough, or should it go to 0.4?

**Comment by dlfivefifty** [comment]
Definitely 0.4

**Comment by timholy** [comment]
Yeah, that's not great. Let's deal with the issue over in https://github.com/ChrisRackauckas/EllipsisNotation.jl/pull/25

**Comment by mcabbott** [comment]
This PR is reverted in #83, btw.

**Pull request merged**
