### PR TITLE
Drop support for  Julia 0.7

### PR DESCRIPTION
**Pull request by hyrodium**
I think we can drop support for Julia 0.7.

### CODE REVIEW

**Comment by timholy** [comment]
I think this will require a minor version bump, although it's possible that Julia 0.7 is exempted.

**Comment by hyrodium** [comment]
I think dropping support is not a breaking change and it's okay with updating the patch version.

**Comment by hyrodium** [comment]
If we update the minor version bump (with major version 0), I'd like to drop the deprecated methods such as `in(a::AbstractInterval, b::TypedEndpointsInterval{:closed,:closed})`.

**Comment by hyrodium** [comment]
Okay, I'll update the minor version and remove the deprecated methods in this PR.

**Comment by mcabbott** [comment]
The logic, I think, is that bumping only the patch version means there are no intermediate versions you can use to later release bugfix supporting older Julia.

I think there is no chance of doing that, and so would vote for `0.5.5`. Making a breaking change just for this seems like imposing unnecessary hassle on everyone who depends on it.

**Comment by hyrodium** [comment]
I think #83 will also be considered breaking.

**Comment by mcabbott** [comment]
May as well do 1.6, I think. Even if nothing needs it yet, it'll save bumping again when someone thinks of a feature that wants it.

**Comment by timholy** [comment]
We might also consider calling this 1.0?

**Comment by timholy** [comment]
Oh yeah. I vote we just rip those methods out, they seem really busted.

**Comment by timholy** [comment]
We can merge this and then separately decide whether to call the next release 0.6 or 1.0.

**Comment by timholy** [comment]
Thanks @hyrodium !

**Pull request merged**
